[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["Airdropper"]
rpc_endpoints = { mode = "https://mainnet.mode.network"}

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
